version: '3.1'
services:

  keycloak:
    image: jboss/keycloak
    restart: always
    environment: 
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      DB_ADDR: keycloak_db
      DB_VENDOR: ${KEYCLOAK_DB_VENDOR}
      DB_PORT: ${KEYCLOAK_DB_PORT}
      DB_DATABASE: ${KEYCLOAK_DB_NAME}
      DB_USER: ${KEYCLOAK_DB_USER} 
      DB_PASSWORD: ${KEYCLOAK_DB_USER_PASSWORD} 
    ports:
      - 8080:8080
    depends_on: 
      - keycloak_db

  keycloak_db:
    image: mariadb
    restart: always
    volumes:
    - keycloak_db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${KEYCLOAK_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${KEYCLOAK_DB_NAME}
      MYSQL_USER: ${KEYCLOAK_DB_USER} 
      MYSQL_PASSWORD: ${KEYCLOAK_DB_USER_PASSWORD} 
volumes:
  keycloak_db_data:

